#!/usr/bin/env bash
# Flight-design study queue: runs FF3D on each degraded condition, one at a time.
#
# The tiles are already generated by scripts/ff3d_make_tiles_degraded.py in work/ff3d_degraded/<condition>/.
# This script only orchestrates: it copies one condition to the input bucket, calls the container, and moves
# the output to work/ff3d_degraded_out/<condition>/ before the next one. The separation matters because the
# input bucket clears itself and the output bucket is wiped at the start of the next run, taking the
# detections of the previous condition with it.
#
# Usage:
#   bash scripts/run_flight_study.sh                # all conditions
#   bash scripts/run_flight_study.sh ang_10 dens_50 # only the ones listed
#
# Expected time: ~2.8 min per tile, 13 tiles per condition, 8 conditions = ~5 h in total.
# Runs unattended. To follow it: tail -f work/ff3d_degraded_out/run.log

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TILES="$REPO/work/ff3d_degraded"
OUTROOT="$REPO/work/ff3d_degraded_out"
FF3D="$REPO/project/models/FF3D_inference"
BUCKET_IN="$FF3D/FF3D_oracle/bucket_in_folder"
BUCKET_OUT="$FF3D/FF3D_oracle/bucket_out_folder"
LOG="$OUTROOT/run.log"

if [ ! -d "$TILES" ]; then
  echo "tiles not found in $TILES" >&2
  echo "run first: PYTHONPATH=. GREENVISTA_LAZ_DIR=\$PWD/work/lazall python scripts/ff3d_make_tiles_degraded.py" >&2
  exit 1
fi

CONDITIONS=("$@")
if [ ${#CONDITIONS[@]} -eq 0 ]; then
  mapfile -t CONDITIONS < <(find "$TILES" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort)
fi

mkdir -p "$OUTROOT"
echo "=== flight study started at $(date -Is) ===" | tee -a "$LOG"
echo "conditions: ${CONDITIONS[*]}" | tee -a "$LOG"

for cond in "${CONDITIONS[@]}"; do
  src="$TILES/$cond"
  dst="$OUTROOT/$cond"
  if [ -d "$dst" ] && [ -n "$(ls -A "$dst" 2>/dev/null)" ]; then
    echo "[$cond] already has output, skipping" | tee -a "$LOG"
    continue
  fi
  n=$(find "$src" -name '*.laz' | wc -l)
  echo "[$cond] $n tiles, start $(date +%H:%M:%S)" | tee -a "$LOG"

  rm -f "$BUCKET_IN"/*.laz "$BUCKET_IN"/*.ply 2>/dev/null || true
  cp "$src"/*.laz "$BUCKET_IN"/

  # the container accumulates meta_data state between runs and corrupts the names; clear test_list
  find "$FF3D" -name 'test_list*' -delete 2>/dev/null || true

  ( cd "$FF3D/ff3d_forestsens" && CLEAR_OUTPUT_BEFORE_RUN=false bash run_docker_locally.sh ) \
    >>"$LOG" 2>&1

  # ---- output collection: three traps ----
  # 1. bucket_out belongs to ROOT (the container writes into it), so `mv` fails with permission denied:
  #    moving requires write access to the SOURCE directory. `cp` only requires read access, and the files
  #    are 644. With `mv`, a condition reports "0 files saved" after the whole GPU run.
  # 2. the pipeline runs with KEEP_ONLY_ZIP=true, so what is left in bucket_out at the end is NOT the PLYs
  #    but ONE results_<stamp>.zip with the canonical `<tile>_round2.ply` inside. Without unzipping,
  #    the condition folder ends up with no .ply at all and the scorer finds nothing.
  # 3. CLEAR_OUTPUT_BEFORE_RUN=false has no effect: it is exported in the HOST shell, but
  #    run_oracle_pipeline.sh runs INSIDE the container via `docker exec`, which does not forward host
  #    environment variables. So the next condition ALWAYS wipes bucket_out when it starts. That is why the
  #    collection has to happen here, before the next iteration, and has to fail loudly if it comes up empty.
  mkdir -p "$dst"
  cp -a "$BUCKET_OUT"/round_2_after_remove_noise_200/. "$dst"/ 2>/dev/null || true
  find "$BUCKET_OUT" -maxdepth 1 -type f \( -name '*.ply' -o -name '*.zip' \) -exec cp -a {} "$dst"/ \; || true
  for z in "$dst"/*.zip; do
    [ -e "$z" ] || continue
    python3 -c "import sys,zipfile;zipfile.ZipFile(sys.argv[1]).extractall(sys.argv[2])" "$z" "$dst" || true
  done

  n_ply=$(find "$dst" -name '*round2.ply' | wc -l)
  echo "[$cond] end $(date +%H:%M:%S), $(find "$dst" -type f | wc -l) files, $n_ply canonical PLYs" | tee -a "$LOG"
  if [ "$n_ply" -eq 0 ]; then
    echo "[$cond] ERROR: no *round2.ply collected. Aborting instead of burning GPU on the next ones." | tee -a "$LOG"
    exit 1
  fi
done

echo "=== end at $(date -Is) ===" | tee -a "$LOG"
echo
echo "next step, score each condition:"
echo "  PYTHONPATH=. GREENVISTA_LAZ_DIR=\$PWD/work/lazall \\"
echo "    python scripts/exp_flight_study_score.py work/ff3d_degraded_out"
